### ISSUE TITLE
Incorrect highlight color on sharing/prev/next buttons

### ISSUE THREAD

**Issue by jessesquires** [ColinEberhardt/wasmweekly#1]
Hey @ColinEberhardt 😄 

I just noticed that these buttons still highlight in "swift orange".

You'll want to update that here: https://github.com/ColinEberhardt/wasmweekly/blob/master/css/style.css#L149

![screen shot 2017-12-26 at 3 45 31 pm](https://user-images.githubusercontent.com/2301114/34366679-2c6d6344-ea54-11e7-8122-32bc9548ae71.png)

**Comment by ColinEberhardt** [comment]
Thanks for spotting that - much appreciated. Also, thanks again for making your newsletter Jekyll site open source, saved me a lot of time putting this one together.

I'm happy to report it's going well, considering WebAssembly is currently a niche topic, I already have 200 subscribers, and ~650 followers on twitter. Small numbers, but more than I was expecting!

**Comment by jessesquires** [comment]
@ColinEberhardt 😄 You're welcome! Really glad it helped! Sounds like you're off to a great start 😎
