### ISSUE TITLE
Wick 0.16.0 released

### ISSUE THREAD

**Issue by jsoverson** [ColinEberhardt/wasmweekly#102]
Hi @ColinEberhardt. Thanks for all your work on wasmweekly!

I just published [wick 0.16.0](https://github.com/candlecorp/wick/releases/tag/0.16.0), a functional reactive WebAssembly framework. Alongside it comes the first version of the [web client](https://github.com/candlecorp/wick-js) with demos at [wasm.candle.dev/]() that run the same wasm on the web as the CLI.

Hopefully, this is the type of stuff you're looking for. Thanks again!

**Comment by ColinEberhardt** [comment]
Looks interesting, thanks for highlighting - I'll definitely include in the next newsletter. Good luck with it!

https://twitter.com/WasmWeekly/status/1714944097692139620

**Comment by jsoverson** [comment]
Thanks @ColinEberhardt
