### ISSUE TITLE
Podcast: WebAssembly in the Real World (with Lin Clark and Till Schneidereit)

### ISSUE THREAD

**Issue by txus** [ColinEberhardt/wasmweekly#11]
Hi!

Txus from Full Stack Fest here. We just released our newest episode of the official podcast where we talk about WebAssembly. Might be relevant! :)

The full episode is at:
https://shows.pippa.io/full-stack-cast/episodes/lin-clark-with-till-schneidereit

And the tweet where we announced it (it has a snippet of the conversation): https://twitter.com/FullStackFest/status/1120613387501629440?s=20

Thank you!

**Comment by ColinEberhardt** [comment]
published https://github.com/ColinEberhardt/wasmweekly/blob/d0f702c7150d671fc091f987e08f8b34d547b584/_posts/2019-04-26-issue-78.md
