### ISSUE TITLE
Article How to build WebAssembly C# Apps with the Mono AOT and Windows Subsystem for Linux

### ISSUE THREAD

**Issue by sasakrsmanovic** [ColinEberhardt/wasmweekly#12]
https://platform.uno/how-to-build-webassembly-c-apps-with-the-mono-aot-and-windows-subsystem-for-linux/

**Comment by ColinEberhardt** [comment]
published https://github.com/ColinEberhardt/wasmweekly/commit/d794a562ee8bec4f39b32220045c4a0bd6a0ada5
