### ISSUE TITLE
Article: Analysis of Google Keep WebAssembly module​

### ISSUE THREAD

**Issue by pventuzelo** [ColinEberhardt/wasmweekly#15]
Hi @ColinEberhardt ,

I published a blogpost last month about how i have analyze the WebAssembly module used by Google Keep. 
Here is the link: https://webassembly-security.com/google-keep-webassembly-module-analysis/

Would be great if you can share it!
Thanks.

**Comment by ColinEberhardt** [comment]
Thanks @pventuzelo - it's on my list now https://twitter.com/WasmWeekly/status/1162101557237821442
