### ISSUE TITLE
C# REST Client on Wasm

### ISSUE THREAD

**Issue by MelbourneDeveloper** [ColinEberhardt/wasmweekly#16]
Hi. I would like to submit this article:
https://christianfindlay.com/2019/08/15/restclient-net-on-webassembly-c/

Also, here is another article on C# and Wasm:
https://christianfindlay.com/2019/06/29/c-and-webassembly-wasm/

Thankyou!

**Comment by ColinEberhardt** [comment]
Thanks! I've shared it here: https://twitter.com/WasmWeekly/status/1165005543288856576
