### ISSUE TITLE
Introduction to WebAssembly for .NET Developers

### ISSUE THREAD

**Issue by sasakrsmanovic** [ColinEberhardt/wasmweekly#18]
I really feel that we are on the brink of a revolution. It’s still very early in the revolution, but I feel like WebAssembly is going to completely change the way we think of web applications. WebAssembly has slowly been stirring up fire since its creation, but why exactly should you be interested in it?

https://platform.uno/webassembly-for-dot-net-developers/

**Comment by ColinEberhardt** [comment]
> I really feel that we are on the brink of a revolution

I certainly agree! 

> WebAssembly is going to completely change the way we think of web applications

... and blockchain, serverless, and much more besides

[Tweeted](https://twitter.com/WasmWeekly/status/1181476631879340032) and in my queue for this week.
