### ISSUE TITLE
Optimizing WebAssembly Startup Time Article

### ISSUE THREAD

**Issue by steipete** [ColinEberhardt/wasmweekly#2]
Hi there!

We wrote a lengthy article about making WebAssembly faster:
https://pspdfkit.com/blog/2018/optimize-webassembly-startup-performance/

Worth sharing?

**Comment by ColinEberhardt** [comment]
Thanks @steipete - much appreciated: https://github.com/ColinEberhardt/wasmweekly/blob/master/_posts/2018-03-02-issue-21.md#optimizing-webassembly-startup-time

**Comment by steipete** [comment]
Thanks! ❤️
