### ISSUE TITLE
WebAssembly on embedded platforms  (and Arduino!)

### ISSUE THREAD

**Issue by vshymanskyy** [ColinEberhardt/wasmweekly#21]
WebAssembly comes to Raspberry Pi, routers, ESP2, ESP8266 (among others).  
Based on Steven Massey's novel, high-performance interpreter topology, which was basically [evaluated](https://github.com/vshymanskyy/wasm3/blob/master/platforms/README.md) on those platforms:
https://github.com/vshymanskyy/wasm3
Funny thing - it could run in browsers, compiled to wasm itself :)

**Comment by ColinEberhardt** [comment]
That looks awesome - thanks for the submissions. Tweeted and added to the queue for the next newsletter:

https://twitter.com/WasmWeekly/status/1193484818769682432

**Comment by vshymanskyy** [comment]
Thanks! Super excited to hit the issue # 💯 ;)

**Comment by vshymanskyy** [comment]
@ColinEberhardt please merge https://github.com/ColinEberhardt/wasmweekly/pull/22
Thanks!
