### ISSUE TITLE
Article: How to create polyglot HTML/JS/WebAssembly module

### ISSUE THREAD

**Issue by pventuzelo** [ColinEberhardt/wasmweekly#23]
Hi @ColinEberhardt,

I published a blogpost about "How to create polyglot HTML/JS/WebAssembly module"​.
Here is the link: [https://webassembly-security.com/polyglot-webassembly-module-html-js-wasm/](https://webassembly-security.com/polyglot-webassembly-module-html-js-wasm/)

Hope you will like it and share it ;)
Thanks.

**Comment by ColinEberhardt** [comment]
Ha ha, that's a neat idea, I like it :-)

Added to the list: https://twitter.com/WasmWeekly/status/1197629420858748928

**Comment by pventuzelo** [comment]
Thanks ;)
