### ISSUE TITLE
Cybertruck in XAML and running Cross-Platform with WebAssembly

### ISSUE THREAD

**Issue by sasakrsmanovic** [ColinEberhardt/wasmweekly#24]
It simply had to be done – Cybertruck in XAML. See for yourself, and further customize the Cybertruck if you’d like,  in our WebAssembly implementation of Cybertruck. 
https://platform.uno/cybertruck-in-xaml-and-running-cross-platform-with-webassembly/

**Comment by ColinEberhardt** [comment]
Ha ha - very nice! Added to my queue: https://twitter.com/WasmWeekly/status/1202104375503675394
