### ISSUE TITLE
Integrating the universes: JavaScript/SPA/Angular & WebAssembly/Blazor

### ISSUE THREAD

**Issue by ChristianWeyer** [ColinEberhardt/wasmweekly#25]
Coming from both worlds I wrote an article about how to integrate the JS/SPA/Angular and the WebAssembly/Blazor worlds:
"Re-Using Angular components in a Blazor WebAssembly application using Angular Elements - Web Components custom elements, FTW!"

... and yes, the title could not be loaded with even more buzzwords ...

https://twitter.com/christianweyer/status/1213078797819535360?s=20

**Comment by ColinEberhardt** [comment]
That is an epic title! 

An interesting blog post thanks. [Tweeted](https://twitter.com/WasmWeekly/status/1214132953179131904) and added to my list for the end of the week.

**Comment by ChristianWeyer** [comment]
Looks like it didn't make the cut for this week...? ;-)

**Comment by ColinEberhardt** [comment]
Apologies - I missed that one when I was scanning through the tweets. It will definitely go in next week (and if I miss it again, feel free to give me another nudge!)

**Comment by ChristianWeyer** [comment]
Hey, no problem. Thanks for considering!
