### ISSUE TITLE
Article: Fuzzing JavaScript WebAssembly APIs using Dharma/Domato (Chrome/V8)

### ISSUE THREAD

**Issue by pventuzelo** [ColinEberhardt/wasmweekly#26]
Hi @ColinEberhardt,

I just published a new blogpost about "Fuzzing JavaScript WebAssembly APIs using Dharma/Domato (Chrome/V8)"​.
Here is the link: https://webassembly-security.com/fuzzing-wasm-javascript-dharma-chrome-v8/

This technique can also be applied to generate valid wasm/wast to fuzz standalone wasm interpreter/parser ;)

Hope you will like it and share it ;)
Thanks.

**Comment by ColinEberhardt** [comment]
That's a great post - thanks for sharing, added to my queue: https://twitter.com/WasmWeekly/status/1215245404197048321

> This technique can also be applied to generate valid wasm/wast to fuzz standalone wasm interpreter/parser ;)

I'd be interested to see the output of that experiment!

**Comment by pventuzelo** [comment]
Thanks ;)

I will create a blogpost about that in the next few month i think, experiment still in progress !
