### ISSUE TITLE
Blazor Mobile, Uno Platform, and WebAssembly

### ISSUE THREAD

**Issue by sasakrsmanovic** [ColinEberhardt/wasmweekly#27]
Blazor Mobile Bindings allow developers to write Blazor-style syntax that produces Xamarin.Forms UI controls instead of HTML elements, therefore producing native iOS and Android applications.  When layered on top, the Uno Platform can bring this experience to the browser via WebAssembly.

https://platform.uno/blazor-mobile-uno-platform-and-webassembly-piling-up-the-tech/

**Comment by ColinEberhardt** [comment]
Sounds cool!  - https://twitter.com/WasmWeekly/status/1218924744269029376
