### ISSUE TITLE
Fuzzing webassemblyjs npm/nodejs package

### ISSUE THREAD

**Issue by pventuzelo** [ColinEberhardt/wasmweekly#29]
Hi @ColinEberhardt,

I just published a new blogpost last week about fuzzing npm/nodejs package and how i found an OOM/DoS bugs in [webassemblyjs](https://github.com/xtuc/webassemblyjs) library.

Here is the link: https://webassembly-security.com/fuzzing-npm-nodejs-webassembly-parsing-library-with-jsfuzz/

Hope you will like it and share it ;)
Thanks.

**Comment by ColinEberhardt** [comment]
Thanks @pventuzelo - I've added it to my list https://twitter.com/WasmWeekly/status/1225306912901795841
