### ISSUE TITLE
Something strange happens when trying to subscribe to the list 

### ISSUE THREAD

**Issue by jcguarinpenaranda** [ColinEberhardt/wasmweekly#3]
Hello,

I tried to subscribe today to the Webassembly Weekly email list, but with no luck (I think). I attach the following screenshots, that I captured with an example email that reflects exactly what happened to me with my real email.

1. Enter the email:
![captura de pantalla 2018-03-13 a las 9 27 53 p m](https://user-images.githubusercontent.com/7200821/37380252-c8590db0-2705-11e8-9d79-06e726a2d239.png)

2. I get this warning in the console:
![captura de pantalla 2018-03-13 a las 9 28 00 p m](https://user-images.githubusercontent.com/7200821/37380272-dd5d44f6-2705-11e8-949b-a796e79798a9.png)

3. If I go to the link that appears in the warrning I get this:
![captura de pantalla 2018-03-13 a las 9 28 12 p m](https://user-images.githubusercontent.com/7200821/37380276-e8ee45d6-2705-11e8-902d-7086cbbebb9b.png)

4. I never receive the subscription verification email that one usually gets after subscribing to a list (is this an expected behaviour?)

Thank you

**Comment by davidlgj** [comment]
Hi,

I think I got the same problem, 
![image](https://user-images.githubusercontent.com/151694/37552294-71917d8c-29b2-11e8-9eab-7e36b585609b.png)

This happened to me in Firefox, I reloaded the page and it was the same. Then I changed to Chrome and it worked fine, so I think it's a Firefox issue.

**Comment by ColinEberhardt** [comment]
Ah, great, thanks for the extra info - that will help a lot!

**Comment by jcguarinpenaranda** [comment]
Thank you so much. I received the first email already :)


2018-03-17 3:15 GMT-05:00 Colin Eberhardt <notifications@github.com>:
