### ISSUE TITLE
Building .NET AOT for WebAssembly in Visual Studio 

### ISSUE THREAD

**Issue by sasakrsmanovic** [ColinEberhardt/wasmweekly#30]
Building Uno Platform WebAssembly apps in Visual Studio on Windows using Ahead of Time (AOT) compilation is now available in preview in Uno dev branch! The Uno.Wasm.Bootstrap package 1.1-dev.416 package now provides the ability to create AOT, Mixed (AOT+Interpreter) and Interpreter (with Bitcode dependencies) builds on Windows 10, without leaving Visual Studio 2019.

https://platform.uno/blog/build-net-aot-for-webassembly-in-visual-studio-with-uno-platform/

**Comment by ColinEberhardt** [comment]
Thanks for the heads-up, .NET AOT sounds great ... https://twitter.com/WasmWeekly/status/1226833913835905024
