### ISSUE TITLE
Blazor WebAssembly Rest Client

### ISSUE THREAD

**Issue by MelbourneDeveloper** [ColinEberhardt/wasmweekly#31]
Introduces RestClient.Net on the Blazor client-side rendering platform with a sample app that runs C# inside the browser. Use a strongly typed, task based Rest Client with abstractions on Wasm. 

https://christianfindlay.com/2020/02/14/blazor-webassembly-rest-client/

**Comment by ColinEberhardt** [comment]
Thanks for the submission :-)

https://twitter.com/wasmweekly/status/1231159252485623813?s=21
