### ISSUE TITLE
C# interop with C/C++ and Rust in WebAssembly

### ISSUE THREAD

**Issue by sasakrsmanovic** [ColinEberhardt/wasmweekly#36]
In this article, I will walk through how to call some simple C/C++ and Rust code from C# in a WebAssembly app.

https://platform.uno/blog/c-interop-with-c-c-and-rust-in-webassembly/

**Comment by ColinEberhardt** [comment]
thanks - tweeted here https://twitter.com/WasmWeekly/status/1273162692300341248
