### ISSUE TITLE
I've written a post about WebAssembly and data science

### ISSUE THREAD

**Issue by rob-blackbourn** [ColinEberhardt/wasmweekly#38]
Hi,

I've written a blog post on WebAssembly and data-science.

I wondered if it was the sort of thing that was suitable for your news letter.

https://rob-blackbourn.github.io/blog/datascience/data/science/webassembly/wasm/array/arrays/javascript/c/dataframe/2020/06/13/datascience-javascript.html

Rob

**Comment by ColinEberhardt** [comment]
Nice one - tweeted here https://twitter.com/WasmWeekly/status/1273161577563381760
