### ISSUE TITLE
WASM to Go source code

### ISSUE THREAD

**Issue by chrsan** [ColinEberhardt/wasmweekly#41]
Nothing really novel here, but might be interesting. It’s like wasm2c but for Go.

https://github.com/chrsan/wagu

**Comment by ColinEberhardt** [comment]
That's a neat idea, thanks for the suggestion @chrsan - before I add it to the newsletter I think it could do with a better readme. I'd love to see what the output is, but without cloning / building. Perhaps add a few examples in the README?

**Comment by chrsan** [comment]
Sure! I’ll ping you back in a couple of weeks when my vacation with my 3 year old is over and I have the time to fix the README with a couple of samples.

**Comment by ColinEberhardt** [comment]
Nice one - enjoy your vacation 🏝️
