### ISSUE TITLE
webassembly with C

### ISSUE THREAD

**Issue by mkde1** [ColinEberhardt/wasmweekly#42]
Hi there, I only know the C language and so that's why I'll ask the questions below

1-Is it possible to create a web app with using only C language and avoiding to use emscripten? 
2-Have you tried it?
3-If you've tried it what was the results?

**Comment by ColinEberhardt** [comment]
Hi @mkde1 - this isn't a forum for general WebAssembly discussion. Perhaps try asking on Reddit? https://www.reddit.com/r/WebAssembly/
