### ISSUE TITLE
Using WebAssembly Modules in C#

### ISSUE THREAD

**Issue by sasakrsmanovic** [ColinEberhardt/wasmweekly#43]
An article that covers: 
-Implementing custom module validation in an ASP.NET Core MVC web application
-Using Emscripten to create a WebAssembly module that can be used outside the browser
-Using WebAssembly modules in your C# code

https://platform.uno/blog/using-webassembly-modules-in-c/

**Comment by ColinEberhardt** [comment]
Thanks @sasakrsmanovic  - tweeted: https://twitter.com/WasmWeekly/status/1298364787668246531
