### ISSUE TITLE
WebAssembly Beyond The Browser: Running WASM In .NET Core Applications With WASI & Wasmtime

### ISSUE THREAD

**Issue by ChristianWeyer** [ColinEberhardt/wasmweekly#44]
WASM, WASI, and .NET Core. Way beyond the browser.
https://www.thinktecture.com/en/webassembly/with-dotnet/

**Comment by ColinEberhardt** [comment]
That's a really good article thanks, tweeted and added to my list https://twitter.com/WasmWeekly/status/1305764217878982657
