### ISSUE TITLE
blog: state of webassembly in envoy

### ISSUE THREAD

**Issue by bettyjunod** [ColinEberhardt/wasmweekly#45]
sharing this blog to include in the next newsletter
https://www.solo.io/blog/the-state-of-webassembly-in-envoy-proxy/

this blog explains the components of webassembly and envoy and the current state of the interface, spec, and tooling

**Comment by ColinEberhardt** [comment]
Thanks for the submission - shared here https://twitter.com/WasmWeekly/status/1311769172184043531
