### ISSUE TITLE
blog: File Converter uses FFMPEG compiled as WebAssembly to convert many filetypes

### ISSUE THREAD

**Issue by flvplayer** [ColinEberhardt/wasmweekly#48]
Check out our product https://fileconverter.digital/

which is just FFMPEG compiled as WebAssembly.

The benefit of this to the end user is free and unlimited conversions since they are just done in the browser. No file size limits and as many times as you want.

Can we get this featured on the next issue of your newsletter?

**Comment by ColinEberhardt** [comment]
Neat - thanks https://twitter.com/WasmWeekly/status/1317200663907094528

**Comment by flvplayer** [comment]
ah so cool thanks for the mention on Twitter!

**Comment by flvplayer** [comment]
ahhh I was so hoping to see it in the latest newsletter (https://wasmweekly.news/issue-134/)

**Comment by ColinEberhardt** [comment]
The Twitter feed is my queue, it will appear in the next one. Thanks

**Comment by flvplayer** [comment]
that tweet was one of your most popular tweets the past few weeks, so it's definitely newsworthy!
