### ISSUE TITLE
WebAssembly tools, frameworks, and libraries for .NET Developers

### ISSUE THREAD

**Issue by sasakrsmanovic** [ColinEberhardt/wasmweekly#53]
This blog summarizes different tools and libraries that .NET developers can use to build WebAssembly apps.
https://platform.uno/blog/webassembly-tools-frameworks-and-libraries-for-net-developers/

**Comment by ColinEberhardt** [comment]
thanks => https://twitter.com/WasmWeekly/status/1321724101564780544
