### ISSUE TITLE
Reimplement VLC Media Player In Browser (FFMPEG Compiled to WebAssembly)

### ISSUE THREAD

**Issue by bestmediaplayer** [ColinEberhardt/wasmweekly#54]
Open source project trying to replicate VLC Media Player to the Browser based on FFMPEG compiled to WebAssembly.

Demo is at: https://bestmediaplayer.org/
Source code is at https://github.com/bestmediaplayer/mediaplayer

I was insanely proud of this end-result because this has never been done before. I really think this has the potential to be something huge if enough people get to know about it.

**Comment by ColinEberhardt** [comment]
Wow, that is really _really_ impressive, tweeted and will be included this week https://twitter.com/WasmWeekly/status/1329162345420091397

**Comment by bestmediaplayer** [comment]
Yea, when I completed the project, I was like: holy shit, this is going to change the world. This could totally be better than VLC. My mind was really blown when I was wrapping up the project and test-fired the SWF file. I didn't expect it to work, but then it actually played. Mind was blown.

I'd appreciate a link to the website too in your newsletter and not just to the open source repo.
