### ISSUE TITLE
The State of WebAssembly – 2020 and 2021

### ISSUE THREAD

**Issue by sasakrsmanovic** [ColinEberhardt/wasmweekly#55]
Gerard Gallant, the author of the book “WebAssembly in Action”  and a Senior software developer / architect @dovico shares his take on WebAssembly in 2020 and what's in store for 2021. 

https://platform.uno/blog/the-state-of-webassembly-2020-and-2021/

**Comment by ColinEberhardt** [comment]
Thanks - tweeted and in the queue https://twitter.com/WasmWeekly/status/1355167299888689154
