### ISSUE TITLE
Article: A JavaScript optimizer compiler

### ISSUE THREAD

**Issue by carlopi** [ColinEberhardt/wasmweekly#57]
It's about a JavaScript very experimental compiler, but somehow relevant since it's starts where Surma's article about WebAssembly performance ends, but instead of going JS -> AS -> Wasm it's JS -> TS -> C++ -> JS.
I am the author, not sure is very centered for the mailing list, but though you might find it interesting / have feedback:
https://medium.com/leaningtech/a-javascript-optimizing-compiler-3fd3f49bd071

**Comment by ColinEberhardt** [comment]
Thanks @carlopi - not WebAssembly, but interesting! shared here https://twitter.com/WasmWeekly/status/1389463586548948997
