### ISSUE TITLE
CppCast about WebAssembly

### ISSUE THREAD

**Issue by daminetreg** [ColinEberhardt/wasmweekly#6]
Dear @ColinEberhardt,

I just had the chance to give a podcast about the current state of WebAssembly and the tool we build : [nxxm](https://nxxm.github.io/) which is a GitHub connected html5 & c++ compiler.

I wonder if it would make sense to speak about it in WasmWeekly ?

nxxm : https://nxxm.github.io/ 
Podcast : http://cppcast.com/2018/10/damien-buhl/ 
My Talk at CppCon 2018 about WebAssembly (making some room for C++) : https://cppcon2018.sched.com/event/FnKX/c-everywhere-with-webassembly

Warm regards and thank you for the awesome work you do to make WebAssembly known.

**Comment by ColinEberhardt** [comment]
Tweeted here https://twitter.com/WasmWeekly/status/1080840195715534848 - and in my queue!

**Comment by daminetreg** [comment]
Thanks, I'll close it then :+1: In the meantime the video of the talk related C++ Everywhere with WebAssembly was posted https://youtu.be/QPJPS-Jjb-g

Thanks for the great WasmWeekly !
