### ISSUE TITLE
NuGet Package Explorer now a WebApp using WebAssembly

### ISSUE THREAD

**Issue by sasakrsmanovic** [ColinEberhardt/wasmweekly#61]
Available at www.nuget.info, the new solution is a WebAssembly and Uno Platform Web Application which is also available as PWA. More information about how it was implemented is at https://platform.uno/blog/nuget-package-explorer-is-now-a-web-app-powered-by-uno-platform/

**Comment by ColinEberhardt** [comment]
Thanks @sasakrsmanovic - added to the list https://twitter.com/WasmWeekly/status/1421041761821110278
