### ISSUE TITLE
Blog: The State of WebAssembly – 2021 and 2022

### ISSUE THREAD

**Issue by mtmattei** [ColinEberhardt/wasmweekly#64]
sharing this blog to include in the next newsletter
https://platform.uno/blog/the-state-of-webassembly-2021-and-2022/

this blog covers the current state of WebAssembly, looks at the big events of the past year and tries to predict where WebAssembly is going in 2022.

**Comment by ColinEberhardt** [comment]
That's already in my queue ... https://twitter.com/WasmWeekly/status/1480793708001955843

Thank you :-)
