### ISSUE TITLE
Article: A primer on WebAssembly

### ISSUE THREAD

**Issue by divya-mohan0209** [ColinEberhardt/wasmweekly#65]
Sharing this blog authored by me on Medium for inclusion in the next edition of the newsletter: https://blog.devgenius.io/a-primer-on-webassembly-834150fdd7ae

This post is an exhaustive article diving into the whys and hows behind the development of WebAssembly.

**Comment by ColinEberhardt** [comment]
Thank you - added to my queue https://twitter.com/WasmWeekly/status/1481985084823642117
