### ISSUE TITLE
PDF tools in webassembly

### ISSUE THREAD

**Issue by LugPaj** [ColinEberhardt/wasmweekly#67]
hello, 
We compiled our pdf library to webassembly and offer many different functionalities (similar to ilovepdf/smallpdf) in our platform https://pdfstandalone.com/
In this way, basic PDF edition can get done without any uploading or downloading of the processed data. As a result, pdf standalone guarantees a very high standard of data protection and security.
All usecases work really fast - except for the pdf compression, where we are still working on improvements.

It would be very nice, if you report about it inside webassembly new.

**Comment by ColinEberhardt** [comment]
That sounds very cool - I'd be happy to share. However, the website (https://pdfstandalone.com/) isn;t loading for me at the moment.
