### ISSUE TITLE
Learn WebAssembly (Book)

### ISSUE THREAD

**Issue by mikerourke** [ColinEberhardt/wasmweekly#7]
Hi Colin,

I know this is a little delayed considering the publication date, but the book I wrote on WebAssembly was published at the end of September and I would be honored if it could be included in one of the upcoming issues.

The title of the book is **Learn WebAssembly**. It was published by Packt on September 25th.

Here's a link:
https://www.packtpub.com/web-development/learn-webassembly

And here's a brief synopsis:

> In the first definitive guide on WebAssembly, you’ll learn how you can wield this new technology to break through the current barriers of web development and build an entirely new class of performant applications.

Thanks,
Mike Rourke

**Comment by ColinEberhardt** [comment]
Thanks Mike - tweeted here (https://twitter.com/WasmWeekly/status/1080792139511021569) and added to my list

**Comment by mikerourke** [comment]
Thanks, I really appreciate it!

**Comment by ColinEberhardt** [comment]
No worries - took me a little while to get round to posting. GitHub could really do with a 'remind me later' feature!

**Comment by mikerourke** [comment]
I completely understand, thanks again!
