### ISSUE TITLE
Blazor WebAssembly: The Power Of EF Core And SQLite In The Browser – In-Depth

### ISSUE THREAD

**Issue by ChristianWeyer** [ColinEberhardt/wasmweekly#72]
> Rumor has it, this is the dream of many .NET developers: Using SQLite and EF Core in the browser with Blazor WebAssembly. Is this possible? In this article, we will have a look at how you can manage your offline data with the help of SQLite and EF Core by persisting the data with standard browser features and APIs.

https://www.thinktecture.com/en/blazor/ef-core-and-sqlite-in-browser/

**Comment by ColinEberhardt** [comment]
Thanks - added it to the queue https://twitter.com/WasmWeekly/status/1514497367051059201
