### ISSUE TITLE
Article: WebAssembly Everywhere

### ISSUE THREAD

**Issue by byrneml** [ColinEberhardt/wasmweekly#76]
Sharing this article that I wrote for inclusion in the next edition of the newsletter. It dives into what WebAssembly is, WASI, The Component Model (briefly), and some of the use cases/things that could be built with or for WebAssembly. 

https://byrnemluke.com/posts/webassembly

**Comment by ColinEberhardt** [comment]
Thanks, thats a really good article - shared here https://twitter.com/WasmWeekly/status/1540392313679142914
