### ISSUE TITLE
Article on Wasm tail calls (+ PR open on JSC)

### ISSUE THREAD

**Issue by carlopi** [ColinEberhardt/wasmweekly#78]
A colleague at Leaning Technologies wrote an article on his work on implementing tail calls (aka return_call) in JavaScriptCore.

Article: https://medium.com/leaningtech/fantastic-tail-calls-and-how-to-implement-them-8c6bd52fd271
Open PR: https://github.com/WebKit/WebKit/pull/2065

**Comment by ColinEberhardt** [comment]
nice one - lead article in issue 175 https://wasmweekly.news/issue-175/
