### ISSUE TITLE
Bun: new runtime based on JSC

### ISSUE THREAD

**Issue by carlopi** [ColinEberhardt/wasmweekly#79]
Last week was the very beta release for a new JavaScript runtime, based on JavaScriptCore (WebKit/Safari): https://bun.sh/ or https://github.com/oven-sh/bun.

Project is very interesting, heavy focus on performances. It's a JavaScript runtime, alternative to node or deno, but obviously runs also WebAssembly, not sure what's the angle but news in tooling might still be of relevance.

I am not related in any way, project is led by https://github.com/Jarred-Sumner (also very active on Twitter at https://twitter.com/jarredsumner).

**Comment by ColinEberhardt** [comment]
Yeah, I read about Bun, looks very cool. Not really WebAssembly-specific, so haven't included in the newsletter
