### ISSUE TITLE
Article: Uno Platform 4.4 – Wasm Threading, Exception Handling and more

### ISSUE THREAD

**Issue by mtmattei** [ColinEberhardt/wasmweekly#80]
Sharing this article from Uno Platform for inclusion in the next edition of the newsletter. It unpacks the latest release with focus on WebAssembly-related features in Uno Platform ahead of the official .NET 7 support, In particular, the biggest improvements are in the area of WebAssembly Exceptions and Threading support.

https://platform.uno/posts/4.4-wasm-threading-and-exception-handling

**Comment by ColinEberhardt** [comment]
Thanks, shared here https://twitter.com/WasmWeekly/status/1547974448417894402
