### ISSUE TITLE
Article: Building Apps for MS Teams in C# and XAML with Uno Platform

### ISSUE THREAD

**Issue by mtmattei** [ColinEberhardt/wasmweekly#87]
Explore how Uno Platform and WebAssembly make it possible to develop apps running in web version of Microsoft Teams using C# and XAML.

https://platform.uno/blog/building-apps-for-ms-teams-in-c-and-xaml-with-uno-platform/

Thanks

**Comment by ColinEberhardt** [comment]
Thanks @mtmattei  - it's in the queue for publication https://twitter.com/WasmWeekly/status/1613489729445548032
