### ISSUE TITLE
Article: The State of WebAssembly 2022-2023

### ISSUE THREAD

**Issue by mtmattei** [ColinEberhardt/wasmweekly#88]
In our third iteration of the State of WebAssembly, we cover WASM advancements in 2022 and WASM predictions for 2023.

https://platform.uno/blog/the-state-of-webassembly-2022-and-2023/

Thanks

**Comment by ColinEberhardt** [comment]
Great article - really enjoyed that. In the queue: https://twitter.com/WasmWeekly/status/1621094543029374978
