### ISSUE TITLE
Article: Hosting Uno Platform WASM on AWS Amplify

### ISSUE THREAD

**Issue by mtmattei** [ColinEberhardt/wasmweekly#89]
Ttutorial, to deploy the WebAssembly port of an Uno Platform Application from a remote Git repository to [AWS Amplify](https://aws.amazon.com/amplify/).

[Hosting Uno Platform WASM on AWS Amplify](https://reads.davidconoh.me/hosting-uno-platform-wasm-on-aws-amplify?x-host=reads.davidconoh.me)

**Comment by ColinEberhardt** [comment]
Thanks for pointing this out, added to the newsletter queue: https://twitter.com/WasmWeekly/status/1633397967397765123
