### ISSUE TITLE
Article/talk: Introducing Kotlin/Wasm

### ISSUE THREAD

**Issue by bashor** [ColinEberhardt/wasmweekly#92]
Text version: https://seb.deleuze.fr/introducing-kotlin-wasm/
Video: https://www.youtube.com/watch?v=LCtMC_IVCKo

https://twitter.com/wasm_io/status/1641774435504992256

**Comment by ColinEberhardt** [comment]
Thanks for the heads-up, looks like a great intro - queued up: https://twitter.com/WasmWeekly/status/1645705903419564034

**Comment by bashor** [comment]
Thanks!
