### ISSUE TITLE
Article: Performance profiling of WebAssembly modules

### ISSUE THREAD

**Issue by achille-roussel** [ColinEberhardt/wasmweekly#95]
New article about the open source release of a performance profiler for WebAssembly https://blog.stealthrocket.tech/performance-in-the-spotlight-webassembly-profiling-for-everyone/

Thanks for managing the weekly newsletter!

**Comment by ColinEberhardt** [comment]
Nice! I shared wzprof earlier https://twitter.com/WasmWeekly/status/1657291202633367552 - I've also shared your blog post.
