### ISSUE TITLE
Article: Webview2 Support in Uno 4.9

### ISSUE THREAD

**Issue by mtmattei** [ColinEberhardt/wasmweekly#97]
Uno Platform 4.9 brings WebView2 Support, and MediaPlayerElement control for Web (along with Android, iOS, Linx and Windows)

https://platform.uno/blog/4-9-release-media-player-element-on-mobile-web-linux-webview2-support/

thank you for your consideration

**Comment by ColinEberhardt** [comment]
Sorry, missed this one - I've shared your 4.10 update.
