### ISSUE TITLE
Article - Uno Platform 4.10 — .NET MAUI Embedding, 150+ UI Controls, and more

### ISSUE THREAD

**Issue by mtmattei** [ColinEberhardt/wasmweekly#99]
New blog post about Uno Platform 4.10 release which includes some awesome new features and includes Added Security via Browser CSP support for WebAssembly.

https://platform.uno/blog/4-10-release/

Thank you for the consideration

**Comment by ColinEberhardt** [comment]
Thanks for submitting - shared here https://twitter.com/WasmWeekly/status/1701134577660494295?s=20
